name: Contentapi v9 publish

env:
  solution: ./src/UmbracoContentApi/UmbracoContentApi.Umbraco9.csproj

on: 
    push:
        tags:
        - '*.*.*'
    workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1        

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore $solution
      
    - name: Build
      run: dotnet build $solution --no-restore
